FROM maven:3.8.3-openjdk-17 AS build

COPY . .

RUN mvn clean package -DskipTests

FROM openjdk:17.0.2-jdk

COPY --from=build target/order-service*.jar ./app.jar

EXPOSE 8083

ENTRYPOINT [ "java", "-jar", "app.jar"]
