FROM maven:3.8.3-openjdk-17 AS build

COPY . .

RUN mvn clean package -DskipTests

FROM eclipse-temurin:17-jre-alpine

COPY --from=build target/user-service*.jar ./app.jar

EXPOSE 8081

ENTRYPOINT [ "java", "-jar", "app.jar"]
