FROM maven:3.8.3-openjdk-17 as build

COPY . .

RUN mvn clean package -DskipTests

FROM openjdk:17.0.2-jdk

COPY --from=build target/user-service*.jar ./app.jar

EXPOSE 8081

ENTRYPOINT [ "java", "-jar", "app.jar"]
